name: HN Daily Summarizer

on:
  schedule:
    - cron: '0 3 * * *' # UTC +8 时间每天上午11点触发
  workflow_dispatch: 

jobs:
  run-summarizer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock" # 监听 lock 文件变化以更新缓存

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install Dependencies
        run: uv sync --frozen --no-dev

      - name: Run Main Script
        env:
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: uv run src/main.py